#!/bin/bash

set -euo pipefail

SRC="Template/openhab.rb"
DEST_DIR="Formula"

if [[ ! -f "$SRC" ]]; then
  echo "Template file does not exist!"
  exit 1
fi

if [[ ! -d "$DEST_DIR" ]]; then
  mkdir $DEST_DIR
fi

if [[ -z "${OPENHAB_VERSION:-}" ]]; then
  echo "OPENHAB_VERSION env variable missing!"
  exit 1
fi

if [[ -z "${OPENHAB_TESTING_VERSION:-}" ]]; then
  echo "OPENHAB_TESTING_VERSION env variable missing!"
  exit 1
fi

if [[ -z "${OPENHAB_SNAPSHOT_VERSION:-}" ]]; then
  echo "OPENHAB_SNAPSHOT_VERSION env variable missing!"
  exit 1
fi

## Function to convert from kamelCase or PascalCase to kebab-case.
##
##    to_kebab input
##
to_kebab() {
  echo "$1" \
    | sed 's/\([a-z]\)\([A-Z]\)/\1-\2/g' \
    | tr '[:upper:]' '[:lower:]'
}

## Function to generate a Formula from the template.
##
##     process formulaName conflicts distroUrl addOnsUrl OPENHAB_TESTING_EXPLICIT_VERSION
##
process() {
  local formulaName=$1
  local formulaNameAsKebap
  formulaNameAsKebap=$(to_kebab "$formulaName")
  local formulaFile
  formulaFile=$DEST_DIR/$formulaNameAsKebap".rb"
  # Conflicting Formulae
  local conflicts=$2
  # openHAB distribution
  local distroUrl=$3
  local distroTarball
  distroTarball=$(basename "$distroUrl")
  local distroSha
  # openHAB add-ons
  local addOnsUrl=$4
  local addOnsKar
  addOnsKar=$(basename "$addOnsUrl")
  local addOnsSha
  # (Optionally) Explicit version to set
  local explicitVersion=${5:-}

  echo "Building Formula file for $formulaNameAsKebap from template:"

  echo -n "  Downloading distro tarball from $distroUrl ... "
  if curl -sL -o "$distroTarball" "$distroUrl"; then echo "DONE"; else echo "FAILED" && exit 1; fi
  echo -n "  Calculating SHA256 checksum for distro tarball ... "
  distroSha=$(shasum -a 256 "$distroTarball" | awk '{print $1}')
  if [[ -n $distroSha ]]; then echo "DONE: $distroSha"; else echo "FAILED" && exit 1; fi

  echo -n "  Downloading add-ons KAR from $addOnsUrl ... "
  if curl -sL -o "$addOnsKar" "$addOnsUrl"; then echo "DONE"; else echo "FAILED" && exit 1; fi
  echo -n "  Calculating SHA256 checksum for add-ons KAR ... "
  addOnsSha=$(shasum -a 256 "$addOnsKar" 2>/dev/null | awk '{print $1}')
  if [[ -n $addOnsSha ]]; then echo "DONE: $addOnsSha"; else echo "FAILED" && exit 1; fi

  echo -n "  Creating $formulaFile from template ... "
  # Copy template with formula name
  cp $SRC "$formulaFile"

  # Add header
  sed -i "1 i\# DO NOT EDIT MANUALLY. Instead, edit the Template/openhab.rb file." "$formulaFile"

  # Replace placeholders
  sed -i "s|\FORMULA_NAME|$formulaName|g" "$formulaFile"

  if [[ -n $explicitVersion ]]; then
    # Set version explicitly => Homebrew needs explicit version
    sed -i "s|\$VERSION|$explicitVersion|g" "$formulaFile"
  else
    # Remove version field => Homebrew is able to determine version from URL
    sed -i "/version \"\$VERSION\"/d" "$formulaFile"
  fi

  sed -i "s|\$CONFLICTS|$conflicts|g" "$formulaFile"
  sed -i "s|\$DISTRO_URL|$distroUrl|g" "$formulaFile"
  sed -i "s|\$DISTRO_SHA|$distroSha|g" "$formulaFile"
  sed -i "s|\$ADDONS_URL|$addOnsUrl|g" "$formulaFile"
  sed -i "s|\$ADDONS_SHA|$addOnsSha|g" "$formulaFile"
  sed -i "s|\$ADDONS_KAR|$addOnsKar|g" "$formulaFile"
  sed -i "s|\$SERVICE_NAME|$formulaNameAsKebap|g" "$formulaFile"
  echo "DONE"
  echo -e "DONE\n"
}

process \
  "Openhab" "\"openhab-milestone\"" \
  "https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/distro/openhab/$OPENHAB_VERSION/openhab-$OPENHAB_VERSION.tar.gz" \
  "https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/distro/openhab-addons/$OPENHAB_VERSION/openhab-addons-$OPENHAB_VERSION.kar"

# Determine repository and explicit version for openhab-milestone package
if [[ $OPENHAB_TESTING_VERSION == *M+([0-9]) ]]; then
  # Milestone Build:
  OPENHAB_TESTING_REPO="libs-milestone-local"
  # Homebrew needs explicit version
  OPENHAB_TESTING_EXPLICIT_VERSION=$OPENHAB_TESTING_VERSION
elif [[ $OPENHAB_TESTING_VERSION == *RC+([0-9]) ]]; then
  # Release Candidate Build:
  OPENHAB_TESTING_REPO="libs-milestone-local"
else
  # Stable Build:
  OPENHAB_TESTING_REPO="libs-release-local"
fi

process \
  "OpenhabMilestone" "\"openhab\"" \
  "https://openhab.jfrog.io/artifactory/$OPENHAB_TESTING_REPO/org/openhab/distro/openhab/$OPENHAB_TESTING_VERSION/openhab-$OPENHAB_TESTING_VERSION.tar.gz" \
  "https://openhab.jfrog.io/artifactory/$OPENHAB_TESTING_REPO/org/openhab/distro/openhab-addons/$OPENHAB_TESTING_VERSION/openhab-addons-$OPENHAB_TESTING_VERSION.kar" \
  "${OPENHAB_TESTING_EXPLICIT_VERSION:-}"
