#!/bin/bash

set -euo pipefail

SRC="Template/openhab.rb"
DEST_DIR="Formula"

if [[ ! -f "$SRC" ]]; then
  echo "Template file does not exist!"
  exit 1
fi

if [[ ! -d "$DEST_DIR" ]]; then
  mkdir $DEST_DIR
fi

if [[ -z "${OPENHAB_VERSION:-}" ]]; then
  echo "OPENHAB_VERSION env variable missing!"
  exit 1
fi

if [[ -z "${OPENHAB_TESTING_VERSION:-}" ]]; then
  echo "OPENHAB_TESTING_VERSION env variable missing!"
  exit 1
fi

if [[ -z "${OPENHAB_SNAPSHOT_VERSION:-}" ]]; then
  echo "OPENHAB_SNAPSHOT_VERSION env variable missing!"
  exit 1
fi

to_kebab() {
  echo "$1" \
    | sed 's/\([a-z]\)\([A-Z]\)/\1-\2/g' \
    | tr '[:upper:]' '[:lower:]'
}

process() {
  local formulaName=$1
  local formulaFile
  formulaFile=$DEST_DIR/$(to_kebab $formulaName)".rb"
  local conflicts=$2
  # openHAB distribution
  local distroUrl=$3
  local distroTarball
  distroTarball=$(basename "$distroUrl")
  local distroSha
  # openHAB add-ons
  local addOnsUrl=$4
  local addOnsKar
  addOnsKar=$(basename "$addOnsUrl")
  local addOnsSha

  echo -n "Downloading distro tarball from $distroUrl ... "
  if curl -sL -o "$distroTarball" "$distroUrl"; then echo "DONE"; else echo "FAILED" && exit 1; fi
  echo -n "Calculating SHA256 checksum for distro tarball ... "
  distroSha=$(shasum -a 256 "$distroTarball" | awk '{print $1}')
  if [[ -n $distroSha ]]; then echo "DONE: $distroSha"; else echo "FAILED" && exit 1; fi

  echo -n "Downloading add-ons KAR from $addOnsUrl ... "
  if curl -sL -o "$addOnsKar" "$addOnsUrl"; then echo "DONE"; else echo "FAILED" && exit 1; fi
  echo -n "Calculating SHA256 checksum for add-ons KAR ... "
  addOnsSha=$(shasum -a 256 "$addOnsKar" 2>/dev/null | awk '{print $1}')
  if [[ -n $addOnsSha ]]; then echo "DONE: $addOnsSha"; else echo "FAILED" && exit 1; fi

  echo -n "Creating $formulaFile from template ... "
  cp $SRC "$formulaFile"
  sed -i "s|\FORMULA_NAME|$formulaName|g" "$formulaFile"

  if [[ "$formulaName" == "Openhab" ]]; then
    sed -i "/version \"\$VERSION\"/d" "$formulaFile"
  else
    sed -i "s|\$VERSION|$OPENHAB_TESTING_VERSION|g" "$formulaFile"
  fi

  sed -i "s|\$CONFLICTS|$conflicts|g" "$formulaFile"
  sed -i "s|\$DISTRO_URL|$distroUrl|g" "$formulaFile"
  sed -i "s|\$DISTRO_SHA|$distroSha|g" "$formulaFile"
  sed -i "s|\$ADDONS_URL|$addOnsUrl|g" "$formulaFile"
  sed -i "s|\$ADDONS_SHA|$addOnsSha|g" "$formulaFile"
  sed -i "s|\$ADDONS_KAR|$addOnsKar|g" "$formulaFile"
  echo "DONE"
}

process \
  "Openhab" "\"openhab-milestone\"" \
  "https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/distro/openhab/$OPENHAB_VERSION/openhab-$OPENHAB_VERSION.tar.gz" \
  "https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/distro/openhab-addons/$OPENHAB_VERSION/openhab-addons-$OPENHAB_VERSION.kar"
process \
  "OpenhabMilestone" "\"openhab\"" \
  "https://openhab.jfrog.io/artifactory/libs-milestone-local/org/openhab/distro/openhab/$OPENHAB_TESTING_VERSION/openhab-$OPENHAB_TESTING_VERSION.tar.gz" \
  "https://openhab.jfrog.io/artifactory/libs-milestone-local/org/openhab/distro/openhab-addons/$OPENHAB_TESTING_VERSION/openhab-addons-$OPENHAB_TESTING_VERSION.kar"
