name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  OPENHAB_VERSION: 5.0.1
  OPENHAB_TESTING_VERSION: 5.1.0.M1
  OPENHAB_SNAPSHOT_VERSION: 5.1.0

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup environment
        run: sudo -E bash -c set

      - name: "ShellCheck Template/build"
        shell: bash
        run: |
          if shellcheck -x -s bash Template/build; then echo "OK"; else echo "FAILED"; exit 1; fi

  generate-formulae:
    name: Generate Formulae from Template
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'

      - name: Calculate version tag
        run: |
          VERSION_TAG=$(echo "$OPENHAB_VERSION" | sed -E 's/^([0-9]+)\.([0-9]+)\..*/v\1.\2/')
          echo VERSION_TAG="$VERSION_TAG" >> "$GITHUB_ENV"

      - name: Run build script
        run: Template/build

      - name: Check for changed Formulae
        id: formulae-changed-files
        run: |
          set -o pipefail
          changed_files=$(echo -n "$(git diff --name-only HEAD Formula && git ls-files --others --exclude-standard Formula)"|tr '\n' ' ')
          echo changed_files="$changed_files" >> "$GITHUB_OUTPUT"

      - name: Configure Git
        if: github.event_name == 'push' && steps.formulae-changed-files.outputs.changed_files != ''
        run: |
          git config user.name "openhab-bot"
          git config user.email "bot@openhab.org"

      - name: Commit and push
        if: github.event_name == 'push' && steps.formulae-changed-files.outputs.changed_files != ''
        run: |
          git add Formula/*
          git commit -m "[ci] Automated Formulae update"
          git push

      - name: Create or update version tag
        if: github.event_name == 'push' && steps.formulae-changed-files.outputs.changed_files != ''
        run: |
          VERSION_TAG="${{ env.VERSION_TAG }}"

          # Delete local and remote tag if it exists
          if git rev-parse "$VERSION_TAG" >/dev/null 2>&1; then
            echo "Tag $VERSION_TAG already exists, deleting..."
            git tag -d "$VERSION_TAG"
            git push --delete origin "$VERSION_TAG" || true
          fi

          # Create new tag and push
          git tag "$VERSION_TAG"
          git push origin "$VERSION_TAG"

      - name: Upload Formulae
        uses: actions/upload-artifact@v4
        with:
          name: formulae
          path: |
            Formula

  test-bot:
    name: Homebrew Test Bot
    needs: generate-formulae
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-15-intel, macos-26 ]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      # Allow checking Formulae changes without needing the latest formulae changes being commited or pushed (yet)
      - name: Download Formulae
        uses: actions/download-artifact@v5
        with:
          name: formulae
          path: Formula

      # Avoid test-bot picking up template files
      - name: Remove Template files
        run: rm -r Template

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax
      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'
