name: Update Version

on:
  repository_dispatch:
    types: [update-version]
    # Expects version string as client_payload
  workflow_dispatch:
    inputs:
      version:
        description: the version number to update to
        type: string
        required: true

env:
  VERSION_FILE: openhab.version

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TARGET_VERSION: ${{ github.event.inputs.version || github.event.client_payload.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update version in version file
        shell: bash
        run: .github/scripts/update-version ${{ env.TARGET_VERSION }}

      - name: Check for changes
        id: changed-files
        run: |
          set -o pipefail
          changed_files=$(echo -n "$(git diff --name-only HEAD ${{ env.VERSION_FILE }} && git ls-files --others --exclude-standard ${{ env.VERSION_FILE }})"|tr '\n' ' ')
          echo changed_files="$changed_files" >> "$GITHUB_OUTPUT"

      - name: Configure Git
        if: steps.changed-files.outputs.changed_files != ''
        run: |
          git config user.name "openhab-bot"
          git config user.email "bot@openhab.org"

      - name: Commit and push
        if: steps.changed-files.outputs.changed_files != ''
        run: |
          git add ${{ env.VERSION_FILE }}
          git commit -m "[ci] Update openHAB version to ${{ env.TARGET_VERSION }}"
          git push

  build:
    needs: update-version
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      actions: read
      checks: read
      contents: write
      pull-requests: read
